blank_issues_enabled: false
contact_links:
  - name: Add a resource
    url: https://github.com/erkcet/awesome-telegram-bots/blob/main/CONTRIBUTING.md
    about: Read the contribution guidelines and submit a pull request.
